#!/bin/bash
# =============================================================================
# run_08_fedavg_dirichlet_01.sh — FedAvg simulation, Dirichlet α=0.1 (Stage 2)
#
# Requires (Stage 1 cat8 files):
#   $DATASETS/X_train_cat8.csv
#   $DATASETS/y_train_cat8.csv
#   $DATASETS/X_val_cat8.csv
#   $DATASETS/y_val_cat8.csv
#   $DATASETS/X_test_cat8.csv
#   $DATASETS/y_test_cat8.csv
#   $DATASETS/cat8_mapping.json
#
# Requires (Stage 2 partition):
#   experiments/stage2_fl/partitioning/dirichlet_01_client_indices.npz
#   (generated by 09_FL_Partitioning.ipynb — must exist in repo)
#
# Produces:
#   experiments/stage2_fl/fedavg/fedavg_round_log_dirichlet_01.json
#   experiments/stage2_fl/results/fedavg_final_metrics_dirichlet_01.json
#   experiments/stage2_fl/results/fedavg_final_metrics_dirichlet_01.csv
#   experiments/stage2_fl/plots/fedavg_curves_dirichlet_01.png
#
# Submit from project root:
#   cd ~/projects/CICIoT2023 && sbatch slurm/run_08_fedavg_dirichlet_01.sh
# =============================================================================

#SBATCH --job-name=fedavg_dir01
#SBATCH --output=experiments/stage2_fl/fedavg/slurm_%j_dirichlet_01.out
#SBATCH --error=experiments/stage2_fl/fedavg/slurm_%j_dirichlet_01.err
#SBATCH --partition=main
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=15
#SBATCH --time=03:00:00

set -euo pipefail

PROJECT="$HOME/projects/CICIoT2023"
DATASETS="$HOME/datasets/CICIoT2023"
PYTHON="$HOME/ciciot_env/bin/python"

mkdir -p "$PROJECT/experiments/stage2_fl/fedavg" \
         "$PROJECT/experiments/stage2_fl/results" \
         "$PROJECT/experiments/stage2_fl/plots"
cd "$PROJECT"

echo "=== Job info ==="
echo "Job ID    : $SLURM_JOB_ID"
echo "Node      : $SLURMD_NODENAME"
echo "CPUs      : $SLURM_CPUS_PER_TASK"
echo "GPU       : $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null || echo 'not detected')"
echo "Start     : $(date)"
echo ""

module load miniconda/miniconda3

# ── Prerequisite checks: Stage 1 cat8 files ───────────────────────────────────
echo "=== Checking prerequisites ==="
for f in X_train_cat8.csv y_train_cat8.csv \
          X_val_cat8.csv   y_val_cat8.csv   \
          X_test_cat8.csv  y_test_cat8.csv  \
          cat8_mapping.json; do
    if [ ! -f "$DATASETS/$f" ]; then
        echo "ERROR: $DATASETS/$f not found — run Stage 1 pipeline first."
        exit 1
    fi
    echo "  OK  $f"
done

PARTITION_FILE="$PROJECT/experiments/stage2_fl/partitioning/dirichlet_01_client_indices.npz"
if [ ! -f "$PARTITION_FILE" ]; then
    echo "ERROR: $PARTITION_FILE not found — run 09_FL_Partitioning.ipynb first."
    exit 1
fi
echo "  OK  dirichlet_01_client_indices.npz"
echo ""

echo "=== Running 08_fedavg.py (dirichlet_01) ==="
$PYTHON scripts/08_fedavg.py \
    --partition-mode dirichlet_01 \
    --data-dir "$DATASETS"

echo ""
echo "=== Done: $(date) ==="
echo "Outputs:"
ls -lh "$PROJECT/experiments/stage2_fl/fedavg/"  2>/dev/null
ls -lh "$PROJECT/experiments/stage2_fl/results/" 2>/dev/null
ls -lh "$PROJECT/experiments/stage2_fl/plots/"   2>/dev/null
